version: "3.9"

services:
  redis:
    restart: always
    container_name: test_redis
    image: redis/redis-stack:latest
    volumes:
      - redis_volume:/data
    ports:
      - 6379:6379

volumes:
  redis_volume:


